syntax = "proto3";

package types;

option go_package = "github.com/lkaihua/carp/proto/types";

enum EntryType {
  ENTRY_TYPE_DEFAULT = 0;
  ENTRY_TYPE_FOLDER  = 1;
  ENTRY_TYPE_IMAGE   = 2;
  ENTRY_TYPE_VIDEO   = 3;
  ENTRY_TYPE_MUSIC   = 4;
  ENTRY_TYPE_TEXT    = 5;
  ENTRY_TYPE_JSON    = 6;
}

enum ViewCategory {
  VIEW_CATEGORY_DEFAULT = 0;
  VIEW_CATEGORY_PHOTO   = 1;
  VIEW_CATEGORY_MUSIC   = 2;
}

message DisplayItem {
  string name = 1;
  EntryType entryType = 2;
  // item name safe string for url usage, encoded. e.g. `README.MD`
  string urlString = 3;
  string firstName = 4;
  string lastName = 5;
  string modTime = 6;
  int64 modTimeUnix = 7;
  string size = 8;
  int64 sizeInt = 9;
  // Full URL of the item. domain and port included. Useful for file access. e.g. `http://192.168.1.192:8100/README.MD`
  string fullUrl = 10;
  // Relative URL of the item. domain and port excluded. Useful for navigation. e.g. `/README.MD`
  string relativeUrl = 11;
}

message ItemCount {
  int32 countAll = 1;
  int32 countImage = 2;
  int32 countVideo = 3;
  int32 countPhoto = 4;
  int32 countMusic = 5;
}

message DisplayItems {
  repeated DisplayItem data = 1;
}
message CoverImages {
  repeated string data = 1;
}

message CoverVideo {
  string url = 1;
  int64 sizeInt = 2;
}

message CoverVideos {
  repeated CoverVideo data = 1;
}

message FolderContentData {
  optional DisplayItems displayItems = 1;
  optional ViewCategory viewCategory = 2;
  optional ItemCount itemCount = 3;
  optional CoverImages coverImages = 4;
  optional CoverVideos coverVideos = 5;
}