// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: proto/types.proto

package types

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EntryType int32

const (
	EntryType_ENTRY_TYPE_DEFAULT EntryType = 0
	EntryType_ENTRY_TYPE_FOLDER  EntryType = 1
	EntryType_ENTRY_TYPE_IMAGE   EntryType = 2
	EntryType_ENTRY_TYPE_VIDEO   EntryType = 3
	EntryType_ENTRY_TYPE_MUSIC   EntryType = 4
	EntryType_ENTRY_TYPE_TEXT    EntryType = 5
	EntryType_ENTRY_TYPE_JSON    EntryType = 6
)

// Enum value maps for EntryType.
var (
	EntryType_name = map[int32]string{
		0: "ENTRY_TYPE_DEFAULT",
		1: "ENTRY_TYPE_FOLDER",
		2: "ENTRY_TYPE_IMAGE",
		3: "ENTRY_TYPE_VIDEO",
		4: "ENTRY_TYPE_MUSIC",
		5: "ENTRY_TYPE_TEXT",
		6: "ENTRY_TYPE_JSON",
	}
	EntryType_value = map[string]int32{
		"ENTRY_TYPE_DEFAULT": 0,
		"ENTRY_TYPE_FOLDER":  1,
		"ENTRY_TYPE_IMAGE":   2,
		"ENTRY_TYPE_VIDEO":   3,
		"ENTRY_TYPE_MUSIC":   4,
		"ENTRY_TYPE_TEXT":    5,
		"ENTRY_TYPE_JSON":    6,
	}
)

func (x EntryType) Enum() *EntryType {
	p := new(EntryType)
	*p = x
	return p
}

func (x EntryType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EntryType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_types_proto_enumTypes[0].Descriptor()
}

func (EntryType) Type() protoreflect.EnumType {
	return &file_proto_types_proto_enumTypes[0]
}

func (x EntryType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EntryType.Descriptor instead.
func (EntryType) EnumDescriptor() ([]byte, []int) {
	return file_proto_types_proto_rawDescGZIP(), []int{0}
}

type ViewCategory int32

const (
	ViewCategory_VIEW_CATEGORY_DEFAULT ViewCategory = 0
	ViewCategory_VIEW_CATEGORY_PHOTO   ViewCategory = 1
	ViewCategory_VIEW_CATEGORY_MUSIC   ViewCategory = 2
)

// Enum value maps for ViewCategory.
var (
	ViewCategory_name = map[int32]string{
		0: "VIEW_CATEGORY_DEFAULT",
		1: "VIEW_CATEGORY_PHOTO",
		2: "VIEW_CATEGORY_MUSIC",
	}
	ViewCategory_value = map[string]int32{
		"VIEW_CATEGORY_DEFAULT": 0,
		"VIEW_CATEGORY_PHOTO":   1,
		"VIEW_CATEGORY_MUSIC":   2,
	}
)

func (x ViewCategory) Enum() *ViewCategory {
	p := new(ViewCategory)
	*p = x
	return p
}

func (x ViewCategory) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ViewCategory) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_types_proto_enumTypes[1].Descriptor()
}

func (ViewCategory) Type() protoreflect.EnumType {
	return &file_proto_types_proto_enumTypes[1]
}

func (x ViewCategory) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ViewCategory.Descriptor instead.
func (ViewCategory) EnumDescriptor() ([]byte, []int) {
	return file_proto_types_proto_rawDescGZIP(), []int{1}
}

type DisplayItem struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Name      string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	EntryType EntryType              `protobuf:"varint,2,opt,name=entryType,proto3,enum=types.EntryType" json:"entryType,omitempty"`
	// item name safe string for url usage, encoded.
	UrlString   string `protobuf:"bytes,3,opt,name=urlString,proto3" json:"urlString,omitempty"`
	FirstName   string `protobuf:"bytes,4,opt,name=firstName,proto3" json:"firstName,omitempty"`
	LastName    string `protobuf:"bytes,5,opt,name=lastName,proto3" json:"lastName,omitempty"`
	ModTime     string `protobuf:"bytes,6,opt,name=modTime,proto3" json:"modTime,omitempty"`
	ModTimeUnix int64  `protobuf:"varint,7,opt,name=modTimeUnix,proto3" json:"modTimeUnix,omitempty"`
	Size        string `protobuf:"bytes,8,opt,name=size,proto3" json:"size,omitempty"`
	SizeInt     int64  `protobuf:"varint,9,opt,name=sizeInt,proto3" json:"sizeInt,omitempty"`
	// http://192.168.1.192:5173/folder/name.webp
	FullUrl string `protobuf:"bytes,10,opt,name=fullUrl,proto3" json:"fullUrl,omitempty"`
	// /folder/name.webp
	RelativeUrl   string `protobuf:"bytes,11,opt,name=relativeUrl,proto3" json:"relativeUrl,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DisplayItem) Reset() {
	*x = DisplayItem{}
	mi := &file_proto_types_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DisplayItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DisplayItem) ProtoMessage() {}

func (x *DisplayItem) ProtoReflect() protoreflect.Message {
	mi := &file_proto_types_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DisplayItem.ProtoReflect.Descriptor instead.
func (*DisplayItem) Descriptor() ([]byte, []int) {
	return file_proto_types_proto_rawDescGZIP(), []int{0}
}

func (x *DisplayItem) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DisplayItem) GetEntryType() EntryType {
	if x != nil {
		return x.EntryType
	}
	return EntryType_ENTRY_TYPE_DEFAULT
}

func (x *DisplayItem) GetUrlString() string {
	if x != nil {
		return x.UrlString
	}
	return ""
}

func (x *DisplayItem) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *DisplayItem) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

func (x *DisplayItem) GetModTime() string {
	if x != nil {
		return x.ModTime
	}
	return ""
}

func (x *DisplayItem) GetModTimeUnix() int64 {
	if x != nil {
		return x.ModTimeUnix
	}
	return 0
}

func (x *DisplayItem) GetSize() string {
	if x != nil {
		return x.Size
	}
	return ""
}

func (x *DisplayItem) GetSizeInt() int64 {
	if x != nil {
		return x.SizeInt
	}
	return 0
}

func (x *DisplayItem) GetFullUrl() string {
	if x != nil {
		return x.FullUrl
	}
	return ""
}

func (x *DisplayItem) GetRelativeUrl() string {
	if x != nil {
		return x.RelativeUrl
	}
	return ""
}

type ItemCount struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CountAll      int32                  `protobuf:"varint,1,opt,name=countAll,proto3" json:"countAll,omitempty"`
	CountImage    int32                  `protobuf:"varint,2,opt,name=countImage,proto3" json:"countImage,omitempty"`
	CountVideo    int32                  `protobuf:"varint,3,opt,name=countVideo,proto3" json:"countVideo,omitempty"`
	CountPhoto    int32                  `protobuf:"varint,4,opt,name=countPhoto,proto3" json:"countPhoto,omitempty"`
	CountMusic    int32                  `protobuf:"varint,5,opt,name=countMusic,proto3" json:"countMusic,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ItemCount) Reset() {
	*x = ItemCount{}
	mi := &file_proto_types_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ItemCount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ItemCount) ProtoMessage() {}

func (x *ItemCount) ProtoReflect() protoreflect.Message {
	mi := &file_proto_types_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ItemCount.ProtoReflect.Descriptor instead.
func (*ItemCount) Descriptor() ([]byte, []int) {
	return file_proto_types_proto_rawDescGZIP(), []int{1}
}

func (x *ItemCount) GetCountAll() int32 {
	if x != nil {
		return x.CountAll
	}
	return 0
}

func (x *ItemCount) GetCountImage() int32 {
	if x != nil {
		return x.CountImage
	}
	return 0
}

func (x *ItemCount) GetCountVideo() int32 {
	if x != nil {
		return x.CountVideo
	}
	return 0
}

func (x *ItemCount) GetCountPhoto() int32 {
	if x != nil {
		return x.CountPhoto
	}
	return 0
}

func (x *ItemCount) GetCountMusic() int32 {
	if x != nil {
		return x.CountMusic
	}
	return 0
}

type DisplayItems struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []*DisplayItem         `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DisplayItems) Reset() {
	*x = DisplayItems{}
	mi := &file_proto_types_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DisplayItems) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DisplayItems) ProtoMessage() {}

func (x *DisplayItems) ProtoReflect() protoreflect.Message {
	mi := &file_proto_types_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DisplayItems.ProtoReflect.Descriptor instead.
func (*DisplayItems) Descriptor() ([]byte, []int) {
	return file_proto_types_proto_rawDescGZIP(), []int{2}
}

func (x *DisplayItems) GetData() []*DisplayItem {
	if x != nil {
		return x.Data
	}
	return nil
}

type CoverImages struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []string               `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CoverImages) Reset() {
	*x = CoverImages{}
	mi := &file_proto_types_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CoverImages) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CoverImages) ProtoMessage() {}

func (x *CoverImages) ProtoReflect() protoreflect.Message {
	mi := &file_proto_types_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CoverImages.ProtoReflect.Descriptor instead.
func (*CoverImages) Descriptor() ([]byte, []int) {
	return file_proto_types_proto_rawDescGZIP(), []int{3}
}

func (x *CoverImages) GetData() []string {
	if x != nil {
		return x.Data
	}
	return nil
}

type FolderContentData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DisplayItems  *DisplayItems          `protobuf:"bytes,1,opt,name=displayItems,proto3,oneof" json:"displayItems,omitempty"`
	ViewCategory  *ViewCategory          `protobuf:"varint,2,opt,name=viewCategory,proto3,enum=types.ViewCategory,oneof" json:"viewCategory,omitempty"`
	ItemCount     *ItemCount             `protobuf:"bytes,3,opt,name=itemCount,proto3,oneof" json:"itemCount,omitempty"`
	CoverImages   *CoverImages           `protobuf:"bytes,4,opt,name=coverImages,proto3,oneof" json:"coverImages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FolderContentData) Reset() {
	*x = FolderContentData{}
	mi := &file_proto_types_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FolderContentData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FolderContentData) ProtoMessage() {}

func (x *FolderContentData) ProtoReflect() protoreflect.Message {
	mi := &file_proto_types_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FolderContentData.ProtoReflect.Descriptor instead.
func (*FolderContentData) Descriptor() ([]byte, []int) {
	return file_proto_types_proto_rawDescGZIP(), []int{4}
}

func (x *FolderContentData) GetDisplayItems() *DisplayItems {
	if x != nil {
		return x.DisplayItems
	}
	return nil
}

func (x *FolderContentData) GetViewCategory() ViewCategory {
	if x != nil && x.ViewCategory != nil {
		return *x.ViewCategory
	}
	return ViewCategory_VIEW_CATEGORY_DEFAULT
}

func (x *FolderContentData) GetItemCount() *ItemCount {
	if x != nil {
		return x.ItemCount
	}
	return nil
}

func (x *FolderContentData) GetCoverImages() *CoverImages {
	if x != nil {
		return x.CoverImages
	}
	return nil
}

var File_proto_types_proto protoreflect.FileDescriptor

const file_proto_types_proto_rawDesc = "" +
	"\n" +
	"\x11proto/types.proto\x12\x05types\"\xcf\x02\n" +
	"\vDisplayItem\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12.\n" +
	"\tentryType\x18\x02 \x01(\x0e2\x10.types.EntryTypeR\tentryType\x12\x1c\n" +
	"\turlString\x18\x03 \x01(\tR\turlString\x12\x1c\n" +
	"\tfirstName\x18\x04 \x01(\tR\tfirstName\x12\x1a\n" +
	"\blastName\x18\x05 \x01(\tR\blastName\x12\x18\n" +
	"\amodTime\x18\x06 \x01(\tR\amodTime\x12 \n" +
	"\vmodTimeUnix\x18\a \x01(\x03R\vmodTimeUnix\x12\x12\n" +
	"\x04size\x18\b \x01(\tR\x04size\x12\x18\n" +
	"\asizeInt\x18\t \x01(\x03R\asizeInt\x12\x18\n" +
	"\afullUrl\x18\n" +
	" \x01(\tR\afullUrl\x12 \n" +
	"\vrelativeUrl\x18\v \x01(\tR\vrelativeUrl\"\xa7\x01\n" +
	"\tItemCount\x12\x1a\n" +
	"\bcountAll\x18\x01 \x01(\x05R\bcountAll\x12\x1e\n" +
	"\n" +
	"countImage\x18\x02 \x01(\x05R\n" +
	"countImage\x12\x1e\n" +
	"\n" +
	"countVideo\x18\x03 \x01(\x05R\n" +
	"countVideo\x12\x1e\n" +
	"\n" +
	"countPhoto\x18\x04 \x01(\x05R\n" +
	"countPhoto\x12\x1e\n" +
	"\n" +
	"countMusic\x18\x05 \x01(\x05R\n" +
	"countMusic\"6\n" +
	"\fDisplayItems\x12&\n" +
	"\x04data\x18\x01 \x03(\v2\x12.types.DisplayItemR\x04data\"!\n" +
	"\vCoverImages\x12\x12\n" +
	"\x04data\x18\x01 \x03(\tR\x04data\"\xbf\x02\n" +
	"\x11FolderContentData\x12<\n" +
	"\fdisplayItems\x18\x01 \x01(\v2\x13.types.DisplayItemsH\x00R\fdisplayItems\x88\x01\x01\x12<\n" +
	"\fviewCategory\x18\x02 \x01(\x0e2\x13.types.ViewCategoryH\x01R\fviewCategory\x88\x01\x01\x123\n" +
	"\titemCount\x18\x03 \x01(\v2\x10.types.ItemCountH\x02R\titemCount\x88\x01\x01\x129\n" +
	"\vcoverImages\x18\x04 \x01(\v2\x12.types.CoverImagesH\x03R\vcoverImages\x88\x01\x01B\x0f\n" +
	"\r_displayItemsB\x0f\n" +
	"\r_viewCategoryB\f\n" +
	"\n" +
	"_itemCountB\x0e\n" +
	"\f_coverImages*\xa6\x01\n" +
	"\tEntryType\x12\x16\n" +
	"\x12ENTRY_TYPE_DEFAULT\x10\x00\x12\x15\n" +
	"\x11ENTRY_TYPE_FOLDER\x10\x01\x12\x14\n" +
	"\x10ENTRY_TYPE_IMAGE\x10\x02\x12\x14\n" +
	"\x10ENTRY_TYPE_VIDEO\x10\x03\x12\x14\n" +
	"\x10ENTRY_TYPE_MUSIC\x10\x04\x12\x13\n" +
	"\x0fENTRY_TYPE_TEXT\x10\x05\x12\x13\n" +
	"\x0fENTRY_TYPE_JSON\x10\x06*[\n" +
	"\fViewCategory\x12\x19\n" +
	"\x15VIEW_CATEGORY_DEFAULT\x10\x00\x12\x17\n" +
	"\x13VIEW_CATEGORY_PHOTO\x10\x01\x12\x17\n" +
	"\x13VIEW_CATEGORY_MUSIC\x10\x02B%Z#github.com/lkaihua/carp/proto/typesb\x06proto3"

var (
	file_proto_types_proto_rawDescOnce sync.Once
	file_proto_types_proto_rawDescData []byte
)

func file_proto_types_proto_rawDescGZIP() []byte {
	file_proto_types_proto_rawDescOnce.Do(func() {
		file_proto_types_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_types_proto_rawDesc), len(file_proto_types_proto_rawDesc)))
	})
	return file_proto_types_proto_rawDescData
}

var file_proto_types_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_proto_types_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_proto_types_proto_goTypes = []any{
	(EntryType)(0),            // 0: types.EntryType
	(ViewCategory)(0),         // 1: types.ViewCategory
	(*DisplayItem)(nil),       // 2: types.DisplayItem
	(*ItemCount)(nil),         // 3: types.ItemCount
	(*DisplayItems)(nil),      // 4: types.DisplayItems
	(*CoverImages)(nil),       // 5: types.CoverImages
	(*FolderContentData)(nil), // 6: types.FolderContentData
}
var file_proto_types_proto_depIdxs = []int32{
	0, // 0: types.DisplayItem.entryType:type_name -> types.EntryType
	2, // 1: types.DisplayItems.data:type_name -> types.DisplayItem
	4, // 2: types.FolderContentData.displayItems:type_name -> types.DisplayItems
	1, // 3: types.FolderContentData.viewCategory:type_name -> types.ViewCategory
	3, // 4: types.FolderContentData.itemCount:type_name -> types.ItemCount
	5, // 5: types.FolderContentData.coverImages:type_name -> types.CoverImages
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_proto_types_proto_init() }
func file_proto_types_proto_init() {
	if File_proto_types_proto != nil {
		return
	}
	file_proto_types_proto_msgTypes[4].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_types_proto_rawDesc), len(file_proto_types_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_types_proto_goTypes,
		DependencyIndexes: file_proto_types_proto_depIdxs,
		EnumInfos:         file_proto_types_proto_enumTypes,
		MessageInfos:      file_proto_types_proto_msgTypes,
	}.Build()
	File_proto_types_proto = out.File
	file_proto_types_proto_goTypes = nil
	file_proto_types_proto_depIdxs = nil
}
