// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.5
//   protoc               v5.29.3
// source: proto/types.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const protobufPackage = "types";

export enum EntryType {
  ENTRY_TYPE_DEFAULT = 0,
  ENTRY_TYPE_FOLDER = 1,
  ENTRY_TYPE_IMAGE = 2,
  ENTRY_TYPE_VIDEO = 3,
  ENTRY_TYPE_MUSIC = 4,
  ENTRY_TYPE_TEXT = 5,
  UNRECOGNIZED = -1,
}

export function entryTypeFromJSON(object: any): EntryType {
  switch (object) {
    case 0:
    case "ENTRY_TYPE_DEFAULT":
      return EntryType.ENTRY_TYPE_DEFAULT;
    case 1:
    case "ENTRY_TYPE_FOLDER":
      return EntryType.ENTRY_TYPE_FOLDER;
    case 2:
    case "ENTRY_TYPE_IMAGE":
      return EntryType.ENTRY_TYPE_IMAGE;
    case 3:
    case "ENTRY_TYPE_VIDEO":
      return EntryType.ENTRY_TYPE_VIDEO;
    case 4:
    case "ENTRY_TYPE_MUSIC":
      return EntryType.ENTRY_TYPE_MUSIC;
    case 5:
    case "ENTRY_TYPE_TEXT":
      return EntryType.ENTRY_TYPE_TEXT;
    case -1:
    case "UNRECOGNIZED":
    default:
      return EntryType.UNRECOGNIZED;
  }
}

export function entryTypeToJSON(object: EntryType): string {
  switch (object) {
    case EntryType.ENTRY_TYPE_DEFAULT:
      return "ENTRY_TYPE_DEFAULT";
    case EntryType.ENTRY_TYPE_FOLDER:
      return "ENTRY_TYPE_FOLDER";
    case EntryType.ENTRY_TYPE_IMAGE:
      return "ENTRY_TYPE_IMAGE";
    case EntryType.ENTRY_TYPE_VIDEO:
      return "ENTRY_TYPE_VIDEO";
    case EntryType.ENTRY_TYPE_MUSIC:
      return "ENTRY_TYPE_MUSIC";
    case EntryType.ENTRY_TYPE_TEXT:
      return "ENTRY_TYPE_TEXT";
    case EntryType.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

export enum ViewCategory {
  VIEW_CATEGORY_DEFAULT = 0,
  VIEW_CATEGORY_PHOTO = 1,
  VIEW_CATEGORY_MUSIC = 2,
  UNRECOGNIZED = -1,
}

export function viewCategoryFromJSON(object: any): ViewCategory {
  switch (object) {
    case 0:
    case "VIEW_CATEGORY_DEFAULT":
      return ViewCategory.VIEW_CATEGORY_DEFAULT;
    case 1:
    case "VIEW_CATEGORY_PHOTO":
      return ViewCategory.VIEW_CATEGORY_PHOTO;
    case 2:
    case "VIEW_CATEGORY_MUSIC":
      return ViewCategory.VIEW_CATEGORY_MUSIC;
    case -1:
    case "UNRECOGNIZED":
    default:
      return ViewCategory.UNRECOGNIZED;
  }
}

export function viewCategoryToJSON(object: ViewCategory): string {
  switch (object) {
    case ViewCategory.VIEW_CATEGORY_DEFAULT:
      return "VIEW_CATEGORY_DEFAULT";
    case ViewCategory.VIEW_CATEGORY_PHOTO:
      return "VIEW_CATEGORY_PHOTO";
    case ViewCategory.VIEW_CATEGORY_MUSIC:
      return "VIEW_CATEGORY_MUSIC";
    case ViewCategory.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

export interface DisplayItem {
  name: string;
  entryType: EntryType;
  urlString: string;
  firstName: string;
  lastName: string;
  modTime: string;
  modTimeUnix: number;
  size: string;
  sizeInt: number;
}

export interface ItemCount {
  countAll: number;
  countImage: number;
  countVideo: number;
  countPhoto: number;
  countMusic: number;
}

export interface FolderContentData {
  displayItems: DisplayItem[];
  viewCategory: ViewCategory;
  itemCount: ItemCount | undefined;
  coverImage: string[];
}

function createBaseDisplayItem(): DisplayItem {
  return {
    name: "",
    entryType: 0,
    urlString: "",
    firstName: "",
    lastName: "",
    modTime: "",
    modTimeUnix: 0,
    size: "",
    sizeInt: 0,
  };
}

export const DisplayItem: MessageFns<DisplayItem> = {
  encode(message: DisplayItem, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.name !== "") {
      writer.uint32(10).string(message.name);
    }
    if (message.entryType !== 0) {
      writer.uint32(16).int32(message.entryType);
    }
    if (message.urlString !== "") {
      writer.uint32(26).string(message.urlString);
    }
    if (message.firstName !== "") {
      writer.uint32(34).string(message.firstName);
    }
    if (message.lastName !== "") {
      writer.uint32(42).string(message.lastName);
    }
    if (message.modTime !== "") {
      writer.uint32(50).string(message.modTime);
    }
    if (message.modTimeUnix !== 0) {
      writer.uint32(56).int64(message.modTimeUnix);
    }
    if (message.size !== "") {
      writer.uint32(66).string(message.size);
    }
    if (message.sizeInt !== 0) {
      writer.uint32(72).int64(message.sizeInt);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): DisplayItem {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseDisplayItem();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.name = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.entryType = reader.int32() as any;
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.urlString = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.firstName = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.lastName = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.modTime = reader.string();
          continue;
        }
        case 7: {
          if (tag !== 56) {
            break;
          }

          message.modTimeUnix = longToNumber(reader.int64());
          continue;
        }
        case 8: {
          if (tag !== 66) {
            break;
          }

          message.size = reader.string();
          continue;
        }
        case 9: {
          if (tag !== 72) {
            break;
          }

          message.sizeInt = longToNumber(reader.int64());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): DisplayItem {
    return {
      name: isSet(object.name) ? globalThis.String(object.name) : "",
      entryType: isSet(object.entryType) ? entryTypeFromJSON(object.entryType) : 0,
      urlString: isSet(object.urlString) ? globalThis.String(object.urlString) : "",
      firstName: isSet(object.firstName) ? globalThis.String(object.firstName) : "",
      lastName: isSet(object.lastName) ? globalThis.String(object.lastName) : "",
      modTime: isSet(object.modTime) ? globalThis.String(object.modTime) : "",
      modTimeUnix: isSet(object.modTimeUnix) ? globalThis.Number(object.modTimeUnix) : 0,
      size: isSet(object.size) ? globalThis.String(object.size) : "",
      sizeInt: isSet(object.sizeInt) ? globalThis.Number(object.sizeInt) : 0,
    };
  },

  toJSON(message: DisplayItem): unknown {
    const obj: any = {};
    if (message.name !== "") {
      obj.name = message.name;
    }
    if (message.entryType !== 0) {
      obj.entryType = entryTypeToJSON(message.entryType);
    }
    if (message.urlString !== "") {
      obj.urlString = message.urlString;
    }
    if (message.firstName !== "") {
      obj.firstName = message.firstName;
    }
    if (message.lastName !== "") {
      obj.lastName = message.lastName;
    }
    if (message.modTime !== "") {
      obj.modTime = message.modTime;
    }
    if (message.modTimeUnix !== 0) {
      obj.modTimeUnix = Math.round(message.modTimeUnix);
    }
    if (message.size !== "") {
      obj.size = message.size;
    }
    if (message.sizeInt !== 0) {
      obj.sizeInt = Math.round(message.sizeInt);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<DisplayItem>, I>>(base?: I): DisplayItem {
    return DisplayItem.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<DisplayItem>, I>>(object: I): DisplayItem {
    const message = createBaseDisplayItem();
    message.name = object.name ?? "";
    message.entryType = object.entryType ?? 0;
    message.urlString = object.urlString ?? "";
    message.firstName = object.firstName ?? "";
    message.lastName = object.lastName ?? "";
    message.modTime = object.modTime ?? "";
    message.modTimeUnix = object.modTimeUnix ?? 0;
    message.size = object.size ?? "";
    message.sizeInt = object.sizeInt ?? 0;
    return message;
  },
};

function createBaseItemCount(): ItemCount {
  return { countAll: 0, countImage: 0, countVideo: 0, countPhoto: 0, countMusic: 0 };
}

export const ItemCount: MessageFns<ItemCount> = {
  encode(message: ItemCount, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.countAll !== 0) {
      writer.uint32(8).int32(message.countAll);
    }
    if (message.countImage !== 0) {
      writer.uint32(16).int32(message.countImage);
    }
    if (message.countVideo !== 0) {
      writer.uint32(24).int32(message.countVideo);
    }
    if (message.countPhoto !== 0) {
      writer.uint32(32).int32(message.countPhoto);
    }
    if (message.countMusic !== 0) {
      writer.uint32(40).int32(message.countMusic);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ItemCount {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseItemCount();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.countAll = reader.int32();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.countImage = reader.int32();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.countVideo = reader.int32();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.countPhoto = reader.int32();
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.countMusic = reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ItemCount {
    return {
      countAll: isSet(object.countAll) ? globalThis.Number(object.countAll) : 0,
      countImage: isSet(object.countImage) ? globalThis.Number(object.countImage) : 0,
      countVideo: isSet(object.countVideo) ? globalThis.Number(object.countVideo) : 0,
      countPhoto: isSet(object.countPhoto) ? globalThis.Number(object.countPhoto) : 0,
      countMusic: isSet(object.countMusic) ? globalThis.Number(object.countMusic) : 0,
    };
  },

  toJSON(message: ItemCount): unknown {
    const obj: any = {};
    if (message.countAll !== 0) {
      obj.countAll = Math.round(message.countAll);
    }
    if (message.countImage !== 0) {
      obj.countImage = Math.round(message.countImage);
    }
    if (message.countVideo !== 0) {
      obj.countVideo = Math.round(message.countVideo);
    }
    if (message.countPhoto !== 0) {
      obj.countPhoto = Math.round(message.countPhoto);
    }
    if (message.countMusic !== 0) {
      obj.countMusic = Math.round(message.countMusic);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ItemCount>, I>>(base?: I): ItemCount {
    return ItemCount.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ItemCount>, I>>(object: I): ItemCount {
    const message = createBaseItemCount();
    message.countAll = object.countAll ?? 0;
    message.countImage = object.countImage ?? 0;
    message.countVideo = object.countVideo ?? 0;
    message.countPhoto = object.countPhoto ?? 0;
    message.countMusic = object.countMusic ?? 0;
    return message;
  },
};

function createBaseFolderContentData(): FolderContentData {
  return { displayItems: [], viewCategory: 0, itemCount: undefined, coverImage: [] };
}

export const FolderContentData: MessageFns<FolderContentData> = {
  encode(message: FolderContentData, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.displayItems) {
      DisplayItem.encode(v!, writer.uint32(10).fork()).join();
    }
    if (message.viewCategory !== 0) {
      writer.uint32(16).int32(message.viewCategory);
    }
    if (message.itemCount !== undefined) {
      ItemCount.encode(message.itemCount, writer.uint32(26).fork()).join();
    }
    for (const v of message.coverImage) {
      writer.uint32(34).string(v!);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): FolderContentData {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseFolderContentData();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.displayItems.push(DisplayItem.decode(reader, reader.uint32()));
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.viewCategory = reader.int32() as any;
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.itemCount = ItemCount.decode(reader, reader.uint32());
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.coverImage.push(reader.string());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): FolderContentData {
    return {
      displayItems: globalThis.Array.isArray(object?.displayItems)
        ? object.displayItems.map((e: any) => DisplayItem.fromJSON(e))
        : [],
      viewCategory: isSet(object.viewCategory) ? viewCategoryFromJSON(object.viewCategory) : 0,
      itemCount: isSet(object.itemCount) ? ItemCount.fromJSON(object.itemCount) : undefined,
      coverImage: globalThis.Array.isArray(object?.coverImage)
        ? object.coverImage.map((e: any) => globalThis.String(e))
        : [],
    };
  },

  toJSON(message: FolderContentData): unknown {
    const obj: any = {};
    if (message.displayItems?.length) {
      obj.displayItems = message.displayItems.map((e) => DisplayItem.toJSON(e));
    }
    if (message.viewCategory !== 0) {
      obj.viewCategory = viewCategoryToJSON(message.viewCategory);
    }
    if (message.itemCount !== undefined) {
      obj.itemCount = ItemCount.toJSON(message.itemCount);
    }
    if (message.coverImage?.length) {
      obj.coverImage = message.coverImage;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<FolderContentData>, I>>(base?: I): FolderContentData {
    return FolderContentData.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<FolderContentData>, I>>(object: I): FolderContentData {
    const message = createBaseFolderContentData();
    message.displayItems = object.displayItems?.map((e) => DisplayItem.fromPartial(e)) || [];
    message.viewCategory = object.viewCategory ?? 0;
    message.itemCount = (object.itemCount !== undefined && object.itemCount !== null)
      ? ItemCount.fromPartial(object.itemCount)
      : undefined;
    message.coverImage = object.coverImage?.map((e) => e) || [];
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function longToNumber(int64: { toString(): string }): number {
  const num = globalThis.Number(int64.toString());
  if (num > globalThis.Number.MAX_SAFE_INTEGER) {
    throw new globalThis.Error("Value is larger than Number.MAX_SAFE_INTEGER");
  }
  if (num < globalThis.Number.MIN_SAFE_INTEGER) {
    throw new globalThis.Error("Value is smaller than Number.MIN_SAFE_INTEGER");
  }
  return num;
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
